#!/usr/bin/env bash
set -euo pipefail

mode="${1:-dry-run}"
config="${2:-wrangler.production.toml}"
outdir="${3:-../worker-dist-production}"

case "$mode" in
  dry-run|deploy) ;;
  *)
    echo "usage: $0 <dry-run|deploy> [wrangler-config] [outdir]" >&2
    exit 2
    ;;
esac

if ! command -v uv >/dev/null 2>&1; then
  python -m pip install --user uv
  export PATH="$HOME/.local/bin:$PATH"
fi

# pywrangler needs a host venv to resolve dependencies, but that environment is
# a build implementation detail and must never become part of the deployed Worker.
rm -rf .venv-workers python_modules
if [[ "$mode" == "dry-run" ]]; then
  rm -rf "$outdir"
fi

# Pin the Cloudflare Python toolchain. workers-runtime-sdk 1.9.1 adds the
# Python 3.14 rpds/Pydantic entropy import patch needed during Worker snapshotting.
uvx \
  --from "workers-py==1.17.5" \
  --with "workers-runtime-sdk==1.9.1" \
  pywrangler sync --force

if [[ ! -d python_modules ]]; then
  echo "python_modules was not generated by pywrangler sync" >&2
  exit 1
fi

# Cloudflare Python Workers deploy vendored runtime packages from python_modules.
# Removing pywrangler's temporary venv prevents duplicate dependency trees from
# being discovered and uploaded by Wrangler.
rm -rf .venv-workers

if [[ "$mode" == "dry-run" ]]; then
  npx --yes wrangler deploy     --config "$config"     --dry-run     --outdir "$outdir"
else
  npx --yes wrangler deploy     --config "$config"     --keep-vars
fi
